---
  - name: Install metricbeat on the webservers
    hosts: webservers
    become: true
    tasks:
      - name: download metricbeat deb
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      - name: install metricbeat deb
        command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

      - name: drop in metricbeat.yml
        copy:
          src: /etc/ansible/files/metricbeat-config.yml
          dest: /etc/metricbeat/metricbeat.yml

      - name: enable docker module for metricbeat
        command: sudo metricbeat modules enable docker

      - name: metric beat setup
        command: sudo metricbeat setup

      - name: reload systemctl
        command: sudo systemctl daemon-reload

      - name: start metricbeat service
        command: sudo service metricbeat restart

      - name: enable service metricbeat onboot
        systemd:
         name: metricbeat
         enabled: yes