#!/bin/bash

states=('Arizona' 
'Calfornia' 
'Colorado' 
'Georgia' 
'Hawaii')


for state in ${states[@]}
do
	if [ $state = 'Hawaii' ]
	then
		echo "Hawaii is the best!"
	else
		echo "I'm not fond of Hawaii" 
	fi
done


numss={0..9}

for num in ${numss[@]}
do
	if [ $num = 1 ] 
#|| [ $num = 5 ] || [ $num = 7 ]
	then
		echo $num
	else
		echo ""
	fi
done
